services:
  mongo:
    image: mongo:7.0
    container_name: mongo-tp3
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-tp3-data:/data/db          # datos persistentes
      - ./material:/material:ro          # carpeta para los archivos del TP (JSON, JS)
    environment:
      MONGO_INITDB_DATABASE: tours

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-tp3
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH: "false"

volumes:
  mongo-tp3-data:
